I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/venaprologue.rpy", line 59, in script
    $Silver_Hollow.locked = False
  File "game/venaprologue.rpy", line 59, in <module>
    $Silver_Hollow.locked = False
NameError: name 'Silver_Hollow' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/venaprologue.rpy", line 59, in script
    $Silver_Hollow.locked = False
  File "renpy/ast.py", line 923, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2235, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/venaprologue.rpy", line 59, in <module>
    $Silver_Hollow.locked = False
NameError: name 'Silver_Hollow' is not defined

Windows-10-10.0.22000
Ren'Py 7.4.8.1895
AVSC 1.0
Sat Sep 18 16:27:58 2021
